doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: '%env(resolve:MYSQL_DRIVER)%'
                host: '%env(resolve:MYSQL_HOST)%'
                port: '%env(resolve:MYSQL_PORT)%'
                dbname: '%env(resolve:MYSQL_DATABASE)%'
                user: '%env(resolve:MYSQL_USER)%'
                password: '%env(resolve:MYSQL_PASSWORD)%'
                server_version: '%env(resolve:MYSQL_SERVER_VERSION)%'
                charset: utf8mb4
                
            mssql:
                url: '%env(resolve:DATABASE_URL_MSSQL)%'
                
        #identity_generation_preferences:
        #    sequence:
        #        # Mantén tus configuraciones actuales
        #        preferred: auto
            
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        #report_fields_where_declared: true
        #validate_xml_mapping: true
        #naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                        
            mssql:
                connection: mssql
                mappings:
                    MssqlEntities:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Mssql'
                        prefix: 'App\Entity\Mssql'
                        alias: MssqlEntities
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system