knp_paginator:
    page_range: 5                      # Número de páginas mostradas en el navegador
    default_options:
        page_name: page                # Nombre del parámetro de página en la URL
        sort_field_name: sort          # Nombre del parámetro de ordenamiento
        sort_direction_name: direction # Nombre del parámetro de dirección
        distinct: true                 # Asegura resultados únicos
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'     # Template para la paginación
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'                # Template para enlaces ordenables 